#pragma once
#include <cstdint>

namespace dxmt::dxso {

enum class DxsoOpcode : uint32_t {
  Nop          = 0,
  Mov          = 1,
  Add          = 2,
  Sub          = 3,
  Mad          = 4,
  Mul          = 5,
  Rcp          = 6,
  Rsq          = 7,
  Dp3          = 8,
  Dp4          = 9,
  Min          = 10,
  Max          = 11,
  Slt          = 12,
  Sge          = 13,
  Exp          = 14,
  Log          = 15,
  Lit          = 16,
  Dst          = 17,
  Lrp          = 18,
  Frc          = 19,
  M4x4         = 20,
  M4x3         = 21,
  M3x4         = 22,
  M3x3         = 23,
  M3x2         = 24,
  Call         = 25,
  CallNz       = 26,
  Loop         = 27,
  Ret          = 28,
  EndLoop      = 29,
  Label        = 30,
  Dcl          = 31,
  Pow          = 32,
  Crs          = 33,
  Sgn          = 34,
  Abs          = 35,
  Nrm          = 36,
  SinCos       = 37,
  Rep          = 38,
  EndRep       = 39,
  If           = 40,
  Ifc          = 41,
  Else         = 42,
  EndIf        = 43,
  Break        = 44,
  BreakC       = 45,
  Mova         = 46,
  DefB         = 47,
  DefI         = 48,

  TexCoord     = 64,
  TexKill      = 65,
  Tex          = 66,
  TexBem       = 67,
  TexBemL      = 68,
  TexReg2Ar    = 69,
  TexReg2Gb    = 70,
  TexM3x2Pad   = 71,
  TexM3x2Tex   = 72,
  TexM3x3Pad   = 73,
  TexM3x3Tex   = 74,
  Reserved0    = 75,
  TexM3x3Spec  = 76,
  TexM3x3VSpec = 77,
  ExpP         = 78,
  LogP         = 79,
  Cnd          = 80,
  Def          = 81,
  TexReg2Rgb   = 82,
  TexDp3Tex    = 83,
  TexM3x2Depth = 84,
  TexDp3       = 85,
  TexM3x3      = 86,
  TexDepth     = 87,
  Cmp          = 88,
  Bem          = 89,
  Dp2Add       = 90,
  DsX          = 91,
  DsY          = 92,
  TexLdd       = 93,
  SetP         = 94,
  TexLdl       = 95,
  BreakP       = 96,

  Phase        = 0xfffd,
  Comment      = 0xfffe,
  End          = 0xffff,
};

enum class DxsoRegisterType : uint32_t {
  Temp           =  0,
  Input          =  1,
  Const          =  2,
  Addr           =  3,
  Texture        =  3,
  RasterizerOut  =  4,
  AttributeOut   =  5,
  TexcoordOut    =  6,
  Output         =  6,
  ConstInt       =  7,
  ColorOut       =  8,
  DepthOut       =  9,
  Sampler        = 10,
  Const2         = 11,
  Const3         = 12,
  Const4         = 13,
  ConstBool      = 14,
  Loop           = 15,
  TempFloat16    = 16,
  MiscType       = 17,
  Label          = 18,
  Predicate      = 19,
  PixelTexcoord  = 20,
};

enum class DxsoUsage : uint32_t {
  Position        = 0,
  BlendWeight     = 1,
  BlendIndices    = 2,
  Normal          = 3,
  PointSize       = 4,
  Texcoord        = 5,
  Tangent         = 6,
  Binormal        = 7,
  TessFactor      = 8,
  PositionT       = 9,
  Color           = 10,
  Fog             = 11,
  Depth           = 12,
  Sample          = 13,
};

enum class DxsoTextureType : uint32_t {
  Texture2D   = 2,
  TextureCube = 3,
  Texture3D   = 4,
};

enum class DxsoShaderType : uint32_t {
  Vertex = 0,
  Pixel  = 1,
};

enum class DxsoRegModifier : uint32_t {
  None    = 0,
  Neg     = 1,
  Bias    = 2,
  BiasNeg = 3,
  Sign    = 4,
  SignNeg = 5,
  Comp    = 6,
  X2      = 7,
  X2Neg   = 8,
  Dz      = 9,
  Dw      = 10,
  Abs     = 11,
  AbsNeg  = 12,
  Not     = 13,
};

} // namespace dxmt::dxso
